theme: jekyll-theme-minimal
title: Vivian Baars
description: Methodologist | Sociologist | Statistician (to-be)
logo: "/Picture VB.png"
show_downloads: "false"
social-network-links:
  email: "vivianbaars@gmail.com"
  github: vvbrs
  linkedin: vivianbaars
