theme: jekyll-theme-minimal
title: Vivian Baars
description: Methodologist | Sociologist | Statistician (to-be)
logo: "/Picture VB.png"
github_username: vvbrs
linkedin_username: vivianbaars
email: vivianbaars@gmail.com
